### ISSUE TITLE
scc.cmd should be optional

### ISSUE THREAD

**Issue by adeneys** [JakobChristensen/Sitecore.Pathfinder#17]
When Pathfinder creates a new project it creates an scc.cmd file in the project directory so users can easily invoke the compiler without needing it on the path.

The problem is this file contains a path on the local machine to the scc.exe file. This location will likely be different on each developers machine so if this file is put into source control it will cause issues for other developers.

I think devs should instead be encouraged to create a cmd launcher script that includes scc on the path, just like we do with git or VS tools (msbuild, etc). We should have a wiki page on how to set this up. If devs don't want to do that and instead use the scc.cmd, scc.exe can optionally create that file.

**Comment by MartinSvarrer** [comment]
I agree having a hardcoded string in a scc.cmd file is not good when sharing a project on multiple machines.

Actually I am not a fan of adding SCC as a global tool either in the path. What happens when Dev A has version 1.2 and Dev B has version 3.1 installed?

I prefer having the tools used by a project installed locally for each project (through a package manager), and let the project define what version of SCC is used.

I.e NPM allows you to run any dependency installed for the project in the node_modules folder. This makes the package manager the only dependency to the project.

**Comment by JakobChristensen** [comment]
This is now solved by supporting NPM. 

Pathfinder can be installed as an NPM module as executed using 'npm run scc', if the appropriate script is added.

When initializing a new project, Pathfinder will look for the node_modules/sitecore-pathfinder directory, and if found, scc.cmd will contain 'npm run scc'.
