### ISSUE TITLE
Need better handling of error messages from the server

### ISSUE THREAD

**Issue by JakobChristensen** [JakobChristensen/Sitecore.Pathfinder#45]
I was trying to run the import-website task but was getting a very generic error which looked like MVC was having an issue. Digging into the issue I eventually found the issue was to do with configuration. The server couldn’t find the config files so the app instance wasn’t created and errors were thrown. The errors were caught in the webapi task and not forwarded back to the console. As a result, I had no idea why my request was failing. Nothing written in the log file of the server either, so without the code and ability to debug, I would never have worked this issue out.

**Comment by adeneys** [comment]
**Steps to reproduce:**

1. Create a new folder in a location that the ASP.NET user doesn't have access such as inside your users folder
1. Use the `scc` exe to create a new project
    scc new-project
1. Execute the import-website task
    scc import-website
1. A general error such as below is returning to the console

scc.cmd(0,0): information SCC7012: Importing website...
scc.cmd(0,0): error SCC6001: The server returned an error: Server Error in '/' A
pplication.
    Specified argument was out of the range of valid values.Parameter name: valu
e
    Description: An unhandled exception occurred during the execution of the cur
rent web request. Please review the stack trace for more information about the e
rror and where it originated in the code.
    Exception Details: System.ArgumentOutOfRangeException: Specified argument wa
s out of the range of valid values.Parameter name: value
    Source Error:
An unhandled exception was generated during the execution of the current web req
uest. Information regarding the origin and location of the exception can be iden
tified using the exception stack trace below.
    Stack Trace:
[ArgumentOutOfRangeException: Specified argument was out of the range of valid v
alues.
Parameter name: value]
    System.Web.HttpResponse.set_StatusDescription(String value) +4738231
    System.Web.Mvc.HttpStatusCodeResult.ExecuteResult(ControllerContext context)
 +109
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(ILi
st`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerCo
ntext controllerContext, ActionResult actionResult) +90
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(ILi
st`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerCo
ntext controllerContext, ActionResult actionResult) +833
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(ILi
st`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerCo
ntext controllerContext, ActionResult actionResult) +833
    System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(Control
lerContext controllerContext, IList`1 filters, ActionResult actionResult) +81
    System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext contro
llerContext, String actionName) +982
    Sitecore.Mvc.Controllers.SitecoreActionInvoker.InvokeAction(ControllerContex
t controllerContext, String actionName) +42
    System.Web.Mvc.c__DisplayClass22.b__1e() +39
    System.Web.Mvc.Async.AsyncResultWrapper.b__0(IAsyncResult asyncResult, Actio
n action) +21
    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +53
    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncRe
sult) +36
    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
    System.Web.Mvc.MvcHandler.b__5(IAsyncResult asyncResult, ProcessRequestState
 innerState) +44
    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncRe
sult) +65
    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionSte
p.Execute() +399
    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& complet
edSynchronously) +137
    Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Ver
sion:4.6.1069.1

The root cause of the error is due to the fact the server component can't access the configuration files. This can be witness by debugging the server assembly during the execution of the task above. Inside the `Startup` class (line 94) a call is made to `RegisterConfiguration`
    var configuration = this.RegisterConfiguration(ToolsDirectory, ProjectDirectory, ConfigurationOptions);

This call includes a try/catch, but the exception is wrotten to the Console, not the console service, so it's hidden from the user as this is running on the server.

**Comment by JakobChristensen** [comment]
No longer relevant.
